name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        SECRET_KEY: supersecretkey
        ALGORITHM: HS256
        ACCESS_TOKEN_EXPIRE_MINUTES: 60
        DATABASE_URL: "sqlite:///./test.db"
        PROJECT_NAME: BankBase
      run: |
        pytest

    - name: (Optional) Build Docker image
      run: |
        docker build -t bankbase:latest .
